### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by LuukVroegop** [Florianisme/WakeOnLan#10]
The shortcuts feature doesn't work for me. No shortcuts show up, even though I have added my PC in the app.
![Screenshot_20230523-012500](https://github.com/Florianisme/WakeOnLan/assets/134341551/e6895d96-ca8c-443e-9c47-6309b62c47e4)

**Comment by Florianisme** [comment]
Hi, you joined the beta right? I'll release a new version later today where all the changes will be moved from beta to the production channel.

**Comment by LuukVroegop** [comment]
Yeah, I did join the beta channel. Thanks! Would love that.

**Comment by Florianisme** [comment]
Can you download the newest beta again? It should be version 1.8.1

**Comment by Florianisme** [comment]
Haven't heard of this feature not working from anywhere else so I'm closing this issue for now.
