### ISSUE TITLE
List of optional options could have lower priority

### ISSUE THREAD

**Issue by fabianski7** [Florianisme/WakeOnLan#12]
~~Your app works great for sending the packet through devices over the local network, but I couldn't do it when I'm not on the internal network.~~

~~I tested the same configuration that I use (and that works) [in this app](https://play.google.com/store/apps/details?id=com.bitklog.wolon).~~

**Comment by Florianisme** [comment]
Hi, that's odd. Especially if it's the same configuration. What's the Broadcast Address that you are using if you are waking your devices from the public internet (I don't want your actual value, just which device's address it is).

Is it for example the public IP of your router?

**Comment by Florianisme** [comment]
Ah, glad it's not actually a programming error :)
Yeah that could be an improvement. 

The idea was that the status IP would be filled out so commonly that it doesn't make sense to hide it besides other options.
I could however also add a small explanation below it, I'll see if that works.

**Comment by Florianisme** [comment]
What's your opinion on this? I also added a short explanation to the input
![image](https://github.com/Florianisme/WakeOnLan/assets/7106869/55f50274-8502-4e9d-a7f8-7232d23c02b5)

**Comment by Florianisme** [comment]
Part of Beta 1.8.3 which rolled out right now

**Comment by Florianisme** [comment]
I'll keep this open until it is published in production. Just to keep track :)

**Comment by Florianisme** [comment]
Released with 1.9.0
