### ISSUE TITLE
App issues WoL requests to all devices

### ISSUE THREAD

**Issue by webartifex** [Florianisme/WakeOnLan#13]
Hi. I'm currently trying out this app and I like it.

Question: Not sure if this is a bug, whenever I just open the app (i.e., *not* pushing the "Turn on" buttons in the app), moments later my workstations all turn on. Is this the expected behavior?

**Comment by Florianisme** [comment]
Hi, did you configure a "status IP" for all of the devices?

**Comment by Florianisme** [comment]
Is this still happening for you? I would close the issue otherwise
