### ISSUE TITLE
Feature request allow custom port

### ISSUE THREAD

**Issue by Shuna322** [Florianisme/WakeOnLan#15]
Personally, I use WoL over Ethernet and to improve some security I try to use unconventional ports. Could you add this feature to the app?

**Comment by Florianisme** [comment]
Hi,

some users had that request before but I always argued that it might increase complexity (on an already complex topic) and that security should not rely on choosing a different port.
But I'll have a think about it.

On a side note: Wouldn't a port scanner expose the different port anyways?

**Comment by Florianisme** [comment]
Will be part of the next beta release 1.9.1 which should launch in the next few hours/days :)

**Comment by manusfreedom** [comment]
Tested, it works well!
