### ISSUE TITLE
[Feature request] support wake on WAN via VPN

### ISSUE THREAD

**Issue by chuwza** [Florianisme/WakeOnLan#17]
Hello, could you please support wake on WAN via VPN ?

Currently, Wake On Lan (Android https://play.google.com/store/apps/details?id=co.uk.mrwebb.wakeonlan) 
![Screenshot_20230814-123548_Wake_On_Lan (小)](https://github.com/Florianisme/WakeOnLan/assets/30049891/c75e9fcc-7518-4eb8-97e5-6c30d1459b38)
and MagicPacket (Windows https://apps.microsoft.com/store/detail/magicpacket/9WZDNCRCW1MX?hl=en-us&gl=us)
![屏幕截图(257)](https://github.com/Florianisme/WakeOnLan/assets/30049891/4f0c4089-25de-4d53-9471-6583879fe7bf)
support using the same configurations to be able to wake the device on both LAN and WAN (VPN). Hopefully this APP will support this feature(currently it requires two configurations for LAN and WAN)
![Screenshot_20230814-123531_Wake_on_Lan (小)](https://github.com/Florianisme/WakeOnLan/assets/30049891/c82220b1-8252-41c2-aa00-dd11c37049ab)

I found how thist two APPs Implementing this feature: I downloaded MagicPacket on Windows and found that it can automatically detect and select whether to use Wake on LAN or Wake on WAN, and even can sends both Wake on LAN and Wake on WAN at the same time.
![屏幕截图(259)](https://github.com/Florianisme/WakeOnLan/assets/30049891/b80d0fac-290a-4d42-b595-3401e4289dee)

**Comment by Florianisme** [comment]
Yes, I had something similar in mind where the user optionally can set a broadcast address for use in LAN but then the app automatically retrieves the Broadcast address for use in VPN as well. So it would essentially send two Wake requests

**Comment by chuwza** [comment]
> 

OK, I'll wait for it, thank you for your app and work👍

**Comment by chuwza** [comment]
> Yes, I had something similar in mind where the user optionally can set a broadcast address for use in LAN but then the app automatically retrieves the Broadcast address for use in VPN as well. So it would essentially send two Wake requests

OK, I'll wait for it, thank you for your app and work👍

**Comment by Florianisme** [comment]
Will be available in the beta version released today

**Comment by chuwza** [comment]
> Will be available in the beta version released today

Thank you, I'll try it

**Comment by Florianisme** [comment]
Update is finally out now!

**Comment by chuwza** [comment]
> Update is finally out now!

I tested 1.8.4 under WireGuard but both WOL and SSH functions failed, and SSH function even also failed in LAN. 
(this is my config)
![Screenshot_20230823-075959_Wake_on_Lan](https://github.com/Florianisme/WakeOnLan/assets/30049891/e7307f56-7312-43d2-8690-0f3ee5a0c0c1)
![Screenshot_20230823-080004_Wake_on_Lan](https://github.com/Florianisme/WakeOnLan/assets/30049891/e2c4fb5e-5a75-4a49-b340-ea9e9c92602d)

But I am successful with this WOL APP (https://play.google.com/store/apps/details?id=co.uk.mrwebb.wakeonlan&hl=en_US) and this SSH APP (https://play.google.com/store/apps/details?id=com.matungos.sshing.free&hl=en_US) on LAN and WAN. 

So I think the problem comes from Wake on lan app

**Comment by Florianisme** [comment]
Does the SSH command prompt you to enter your password when you execute it using the SSH app?

**Comment by chuwza** [comment]
> Does the SSH command prompt you to enter your password when you execute it using the SSH app?

No, it doesn't.

The password is already entered in the configuration, so maybe it's normal that there's no prompt?
![41208412 (小)](https://github.com/Florianisme/WakeOnLan/assets/30049891/696a042d-6e83-4760-a03c-0b0cd2ed5e5d)

**Comment by Florianisme** [comment]
In this case, the password is only used for login. So you also don't have to execute the same command using ``sudo``?

**Comment by chuwza** [comment]
> In this case, the password is only used for login. So you also don't have to execute the same command using `sudo`?

sudo? Oh! My device is Windows, so that's the cause? this ssh function only support Linux?

**Comment by Florianisme** [comment]
Yes, it's only supported on Linux :) It's a bit worriying that the dialog says that a user session was successfully initiated though..

**Comment by chuwza** [comment]
> Yes, it's only supported on Linux :) It's a bit worriying that the dialog says that a user session was successfully initiated though..

Sorry, I don't know much about it, maybe the ssh command for ssh to Windows Server and Linux Server is the same, so it shows user session was successfully create

**Comment by Florianisme** [comment]
Got it. But you've mentioned that wakeups still dont work when you leave the Broadcast address empty?

**Comment by chuwza** [comment]
> Got it. But you've mentioned that wakeups still dont work when you leave the Broadcast address empty?

The app prompt me that value cannot be null
![Screenshot_20230823-150452_Wake_on_Lan (小)](https://github.com/Florianisme/WakeOnLan/assets/30049891/5a50fce4-4663-4687-8dcb-e972346cb971)

**Comment by Florianisme** [comment]
But that's not the beta version, the "Remote shutdown" is missing.
Only in the beta the input field is not required

**Comment by chuwza** [comment]
> But that's not the beta version, the "Remote shutdown" is missing. Only in the beta the input field is not required

I can't download beta version, did you withdraw this update? I was able to download it a couple hours ago, and now even though it's beta, it downloaded as 1.8.0

**Comment by Florianisme** [comment]
No I didn't.. That's weird

**Comment by chuwza** [comment]
> No I didn't.. That's weird

Oh, I cleared my Play Store cache and 1.8.4 is back!
And I test the leave the Broadcast address empty, It still can't work

**Comment by chuwza** [comment]
> Would be willing to try a custom version which I provide to you as an APK file?

Yes, I'd like to try it.

**Comment by Florianisme** [comment]
Alright, I will provide you one in the following days! Thanks!

**Comment by chuwza** [comment]
> Alright, I will provide you one in the following days! Thanks!

> Alright, I will provide you one in the following days! Thanks!

OK, I'll wait for it, thank you too

**Comment by Florianisme** [comment]
[app-release.zip](https://github.com/Florianisme/WakeOnLan/files/12479008/app-release.zip)
Please try this one. I have to zip it because Github restricts file types for uploads.

This version tries to send wake packets to all connected interfaces of your phone. Normally I am filtering interfaces by their name to some known working ones. But maybe in your case that interface name is not in the list when you are connected via VPN.

**Comment by chuwza** [comment]
> 

Hello, It didn't work.

Maybe this information is useful.
In my LAN, OpenWrt ip is 192.168.1.1, NAS ip is 192.168.1.2. 
In WireGuard LAN(WireGuard install on OpenWrt), WireGuard ip is 192.168.2.1, my phone ip is 192.168.2.2, and phone can access all devices in LAN
