### ISSUE TITLE
Does not seem to work across subnets

### ISSUE THREAD

**Issue by ThaDaVos** [Florianisme/WakeOnLan#18]
Normally I use WakeMeOnLan from Nirsoft (https://www.nirsoft.net/utils/wake_on_lan.html) to wake up my linux box - now I trying to do the same with the app, but for some reason it cannot wake it up - even if I set the settings the same:

name: hostname of box
mac address: mac address of box
port: 9
broadcast: 255.255.255.255 (as this is the only one which works in Nirsofts app, you can select from the ones shown below)
status: ip of box

but for some reason it doesn't react to it - I've checked my firewall settings, PC is connected to same network so that can't be it.

Options in WakeMeOnLan:
![afbeelding](https://github.com/Florianisme/WakeOnLan/assets/5251028/b126a837-7824-4c02-aea0-f3b752e820ab)

**Comment by Florianisme** [comment]
Can you try with the newest Beta release? Leave the Broadcast address blank

**Comment by ThaDaVos** [comment]
I would love too - but after updating to Beta the app won't launch

**Comment by Florianisme** [comment]
Yes I found the culprit and will release an update soon. Did the it work for you with the Beta 1.8.4?

**Comment by ThaDaVos** [comment]
It does when I am on the same subnet - apparently the issue is inside the Unifi Dream Machine... it supports cross subnet WOL on it's on switch but it's own switch only - so if there's a device inbetween, like an extra switch or AP it does not work

**Comment by Florianisme** [comment]
Interesting. And because you were testing from (what looks like a Windows machine) before it was not an issue because it's connected via LAN?

**Comment by ThaDaVos** [comment]
I was testing from a Windows server (through RDS Remote Apps) and that server happens to be straight up connected to the Unifi Dream Machine owns internal switch, just like the machine I'm trying to turn on - so that's why cross-aubnet wol works there - should also work if I add a switch in between and connect them both to it though

**Comment by Florianisme** [comment]
Yes indeed, but seeing that it's not a general issue with this app I assume this issue can be closed?

**Comment by ThaDaVos** [comment]
Yeah I will close it
