### ISSUE TITLE
App sends Magic Packet automatically when in VPN

### ISSUE THREAD

**Issue by minion190422** [Florianisme/WakeOnLan#23]
I'm connecting to my home network via WireGuard. As soon as I'm opening the app a magic packet is send to the remote sleeping client which is turned on. Furthermore, if the app is opened in the background and the VPN is turned on, it also sends magic packets all the time and starts the client unintentionally.
Being connected to the local WiFi everything works as expected. The remote client starts as soons as I click the button and at no other time.

I'd love the app to work the same way, whether I'm connected directly to the local network via WiFi or via VPN (WireGuard).

**Comment by Florianisme** [comment]
Hi, it does send ping packets to the clients. Could it be that maybe your router interprets these pings as wake up requests and turns on the device?

Can you try to remove the "status IP" of the affected devices and try again?

**Comment by minion190422** [comment]
Hi Florian,

you're right, this disables the described behaviour. But I'm not able to turn on the remote client via VPN connection at all now.
