### ISSUE TITLE
Shutdown feature is not specific to only Linux.

### ISSUE THREAD

**Issue by Sahil12524** [Florianisme/WakeOnLan#26]
![Screenshot_20231023_073448_Chrome](https://github.com/Florianisme/WakeOnLan/assets/42999635/70ae4c7b-4810-4f78-ace9-188f40b69f51)

I found a article that can enable SSHD on Windows OS.
https://www.hanselman.com/blog/how-to-ssh-into-a-windows-10-machine-from-linux-or-windows-or-anywhere
Currently I am personally using the feature on Windows and it is just working fine.
![Screenshot_20231023_073636_Wake on Lan](https://github.com/Florianisme/WakeOnLan/assets/42999635/11cc4bdd-0f6b-4a9e-80f3-5b8cc829d7b5)

**Comment by Florianisme** [comment]
Hi, thanks for letting me know!
To my surprise someone already mentioned that on a Google Play Review. I honestly did not know that would work 😄

**Comment by Alzhunter** [comment]
Curios, I've *basically* gotten this to work, at least a random ssh android client on my Phone with identical inputs can execute the shutdown command, not the app however. I'm using what I assume is 1.9 or whatever version the Play store beta program gives you. The "test shutdown button" shows that I can't even connect to my pc. In case anybody is interested, I can of course attach some screenshots to this thread

**Comment by Shihabus-Sakib-Rad** [comment]
For windows, this works for me
`shutdown /s /f /t 0`

**Comment by Sahil12524** [comment]
> For windows, this works for me `shutdown /s /f /t 0`

Tbh i am using this same command from almost 2 years now and yes it works well.
Thanks for the information though.
