### ISSUE TITLE
Request: upload to F-Droid

### ISSUE THREAD

**Issue by wpwpwpwpw** [Florianisme/WakeOnLan#31]
Hi!
I've been using your app. However, it would be great to have it available at the F-Droid repository. Would that be possible?
Thank you a lot!

**Comment by AdrienChatelain** [comment]
I'd like to second that, or ask if there is/could be an official APK available?

**Comment by Florianisme** [comment]
Good idea!
@AdrienChatelain yes I always upload APKs which are released to the production channel in the [releases on Github](https://github.com/Florianisme/WakeOnLan/releases) :)

**Comment by mguinness** [comment]
It's also on [Izzydroid](https://apt.izzysoft.de/fdroid/index/apk/de.florianisme.wakeonlan) as discussed in [Publish on F-Droid/Izzydroid](https://github.com/Florianisme/WakeOnLan/issues/1).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Florianisme/WakeOnLan/issues/31#issuecomment-1848655853

@mguinness, [`gitlab.com/search?search=Florianisme&nav_source=navbar&project_id=36528&group_id=28397&search_code=true&repository_ref=90b896e0b54af5671be161679e2fbd179c01e6e2`](https://gitlab.com/search?search=Florianisme&nav_source=navbar&project_id=36528&group_id=28397&search_code=true&repository_ref=90b896e0b54af5671be161679e2fbd179c01e6e2) doesn't return anything. I don't believe that we can consider this complete until it's in [`gitlab.com/fdroid/fdroiddata/-/tree/master/metadata`](https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata?ref_type=heads).

**Comment by Florianisme** [comment]
I'll have to take a look at this at a later stage! Currently the releases are published right here on Github and I don't know how well publishing on FDroid would integrate into my release workflow.

**Comment by B0ycee** [comment]
@Florianisme would be great if you can take another look at including this app in the native F-droig catalogue!
