### ISSUE TITLE
Feature request: Widgets with state

### ISSUE THREAD

**Issue by DrStrangeloovee** [Florianisme/WakeOnLan#33]
I think it would be a nice addition to have widgets which function as a button to turn on/off the device. Additionally they could represent the current state by displaying an appropriate icon.
Example how this [App](https://play.google.com/store/apps/details?id=co.uk.mrwebb.wakeonlan) is doing it:
![Screenshot_20240130-170054.png](https://github.com/Florianisme/WakeOnLan/assets/16350441/fbe79244-3bc1-4859-ac11-a753b1959a50)

**Comment by Florianisme** [comment]
Currently there are no plans on adding widgets to the app, so I'm closing this for now.
