### ISSUE TITLE
Feature request: Add custom code to executebon the system after connecting using ssh

### ISSUE THREAD

**Issue by xemulat** [Florianisme/WakeOnLan#34]
Kinda self explainatory, it would widen the supported operating systems range.

**Comment by Florianisme** [comment]
Hi, what exactly do you mean? Can't you enter multiple commands and combine them using the && operator?

**Comment by xemulat** [comment]
![ResizedImage_2024-04-06_18-19-58_1781](https://github.com/Florianisme/WakeOnLan/assets/98595166/e3716652-d2c6-4b8b-8917-02561f516cdf)

It's this text, that it works only on Linux related systems.

**Comment by Florianisme** [comment]
It actually also works on Windows machines, see #26

**Comment by xemulat** [comment]
Oh! Thank you for the quick response!
