### ISSUE TITLE
Shortcut Feature 

### ISSUE THREAD

**Issue by NickelAnierr** [Florianisme/WakeOnLan#4]
It would be convenient to use [shortcuts](https://developer.android.com/develop/ui/views/launch/shortcuts)  on the home screen to turn on the PC.
 
![1_gfQYi_piiZ96d5XmObwOiQ](https://user-images.githubusercontent.com/36328987/221154442-cc22ebfa-fbf8-48e2-b936-444245067345.png)

**Comment by Florianisme** [comment]
I really like that idea! Will take a look at it once I find some time!

**Comment by Florianisme** [comment]
@NickelAnierr I started working on this, shouldn't take too long to finish

**Comment by Florianisme** [comment]
Hi, shortcuts are now available in the open beta release (1.7.1)

**Comment by NickelAnierr** [comment]
Oh, that's cool. Thanks!

**Comment by Florianisme** [comment]
Released to production in 1.8.0
