### ISSUE TITLE
the app is no longer in the google play store

### ISSUE THREAD

**Issue by Obi-Wahn** [Florianisme/WakeOnLan#48]
the app is no longer in the google play store. i would really like to see it return to the store, is there any hope of the app coming back?

https://play.google.com/store/apps/details?id=de.florianisme.wakeonlan

**Comment by Florianisme** [comment]
see #47

**Comment by Obi-Wahn** [comment]
thanks for the info. too bad! i'm keeping my fingers crossed that a solution will be found.
