### ISSUE TITLE
Round icon for Android 7.1 / Wear OS 2

### ISSUE THREAD

**Issue by rodrigoswz** [Florianisme/WakeOnLan#6]
Minor request... just to improve aesthetics among other apps.
Currently Wake On Lan has a square icon, it would be better if it was round.

![Watch_Screenshot_230316-093812](https://user-images.githubusercontent.com/14058427/225624346-f971fc99-411d-4ba3-a19a-f56f51e5dd37.jpeg)

**Comment by Florianisme** [comment]
Sorry, the screenshot you attached is from your watch, not from your phone correct?

**Comment by rodrigoswz** [comment]
> Sorry, the screenshot you attached is from your watch, not from your phone correct?

Exactly, from my TicWatch Pro 3 running Wear OS 2 (Android 9 based).

**Comment by rodrigoswz** [comment]
> 

Great, thank you much!

**Comment by Florianisme** [comment]
Released to production in 1.8.0
