### ISSUE TITLE
Consider implementing SSH to allow poweroff and reboot commands. 

### ISSUE THREAD

**Issue by ghost** [Florianisme/WakeOnLan#7]
The app is beautiful and works well. Thanks for sharing it!

I would appreciate an option to power off and reboot a machine as well. [Similar applications](https://github.com/BootBoi/android-app) achieve this with SSH.

**Comment by Florianisme** [comment]
I have been wanting to implement this feature for some time aswell. 
Will be a bigger task for sure as implementing SSH functionality can really be a rabbit hole..

**Comment by Florianisme** [comment]
I have just sent the first shutdown commands to my local machines and it's working well for me :)
I can upload a signed apk here if you want to try it out yourself

**Comment by voidscuttle** [comment]
Sure! That'd be nice.

**Comment by Florianisme** [comment]
Alright, give it a try then. I had to zip it as Github would not allow for me to upload the APK directly.

Looking forward to your feedback!
[app-release.zip](https://github.com/Florianisme/WakeOnLan/files/11065511/app-release.zip)

**Comment by voidscuttle** [comment]
Works well. No issues. Thanks a lot for implementing this!

**Comment by Florianisme** [comment]
Thanks a lot for the feedback! 

Yes the test button is a good idea. 
I thought about implementing a global "protocol" view which would include logs for SSH shutdown and WOL packages.
But I think the test button with a result dialog would suffice for now.

I would keep the issue open until the feature is merged into master :)

**Comment by voidscuttle** [comment]
> One more question: Do you think that the text below the "Command" field is descriptive enough?

Yeah I think it's fine.

**Comment by Florianisme** [comment]
Moving this to the beta channel tonight. Should be available as version 1.8.1

**Comment by Florianisme** [comment]
Note for improvement: "Timeout expired" is shown as an unknown error when executing a command, which triggers the sudo password prompt. Add hint in description and possibly contents of the OutputStream of the command?

**Comment by Florianisme** [comment]
Finally released with 1.9.0
