### ISSUE TITLE
No sponsor button

### ISSUE THREAD

**Issue by Wazzaps** [Florianisme/WakeOnLan#8]
Can't thank you for this app properly :)

**Comment by Florianisme** [comment]
Haha, yeah there isn't one 😄 
But if you want to you can use my Paypal.me Link https://paypal.me/Florianisme

**Comment by Wazzaps** [comment]
Sent :)
You can put this link in a sponsor button using this feature: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

**Comment by Florianisme** [comment]
Seen it, thanks a lot ☺️ 
I'll take a look at it, thanks! :)
